/*
 * Copyright (C) 2016 JDBX
 * 
 * https://github.com/jdlib/JDBX
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at 
 * http://www.apache.org/licenses/LICENSE-2.0.
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package org.jdbx;


/**
 * AutoKeys defines which automatically generated
 * keys should be available for retrieval after execution of a SQL command.
 */
public class AutoKeys
{
	/**
	 * A Builder interface to define which autogenerated keys should be reported.
	 * @param <I> the concrete implementation
	 */
	public static interface Builder<I extends Builder<I>>
	{
		/**
		 * The AutoKeys object should be used.
		 * @param autoKeys the autoKeys or null if no auto generated keys should be returned
		 * @return this
		 */
		public I reportAutoKeys(AutoKeys autoKeys);


		/**
		 * A default AutoKeys object should be used.
		 * @return this
		 */
		public default I reportAutoKeys()
		{
			return reportAutoKeys(new AutoKeys());
		}


		/**
		 * A AutoKeys object based on the column indexes should be used.
		 * @param colIndexes the indexes
		 * @return this
		 */
		public default I reportAutoKeys(int... colIndexes)
		{
			return reportAutoKeys(new AutoKeys(colIndexes));
		}


		/**
		 * A AutoKeys object based on the column names should be used.
		 * @param colNames the names
		 * @return this
		 */
		public default I reportAutoKeys(String... colNames)
		{
			return reportAutoKeys(new AutoKeys(colNames));
		}
	}


	/**
	 * Creates a new AutoKeys object.
	 */
	public AutoKeys()
	{
	}


	/**
	 * Creates a new AutoKeys object.
	 * @param colIndexes the indexes of the key columns which should be reported
	 */
	public AutoKeys(int[] colIndexes)
	{
		Check.notNull(colIndexes, "colIndexes");
		colIndexes_ = colIndexes;
	}


	/**
	 * Creates a new AutoKeys object.
	 * @param colNames the names of the key columns which should be reported
	 */
	public AutoKeys(String[] colNames)
	{
		Check.notNull(colNames, "colNames");
		colNames_ = colNames;
	}


	/**
	 * Returns the column indexes of the keys which should be returned.
	 * @return the indexes or null if this AutoKeys object is not index based
	 */
	public int[] getColIndexes()
	{
		return colIndexes_;
	}


	/**
	 * Returns the column names of the keys which should be returned.
	 * @return the named or null if this AutoKeys object is not name based
	 */
	public String[] getColNames()
	{
		return colNames_;
	}


	private int[] colIndexes_;
	private String[] colNames_;
}
