/*
 * Copyright (C) 2016 JDBX
 * 
 * https://github.com/jdlib/JDBX
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at 
 * http://www.apache.org/licenses/LICENSE-2.0.
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package org.jdbx;


import java.sql.Statement;
import org.jdbx.function.Unchecked;


/**
 * StmtOptions allows to retrieve or set options of a JDBX statement.
 * @see Stmt#options()
 */
public class StmtOptions
{
	StmtOptions(Stmt stmt)
	{
		stmt_ = stmt;
	}


	/**
	 * Sets that the statement is pooled or not pooled.
	 * @param poolable the poolable flag
	 * @return this
	 * @see Statement#setPoolable(boolean)
	 */
	public StmtOptions setPoolable(boolean poolable) throws JdbxException
	{
		set(StmtOption.POOLABLE, Boolean.valueOf(poolable));
		return this;
	}


	/**
	 * Returns if a statement is poolable.
	 * @return the poolable flag
	 * @see Statement#isPoolable
	 */
	public boolean isPoolable() throws JdbxException
	{
		return get(StmtOption.POOLABLE).booleanValue();
	}


	/**
	 * Sets the name of the SQL cursor which will be used by subsequent statement operations.
	 * @param cursorName the name of the cursor
	 * @return this
	 * @see Statement#setCursorName
	 */
	public StmtOptions setCursorName(String cursorName) throws JdbxException
	{
		set(StmtOption.CURSORNAME, cursorName);
		return this;
	}


	/**
	 * Sets the limit for the maximum number of bytes that can be returned for
     * character and binary column values in a result produced by this statement.
	 * @param size the maximum number of bytes
	 * @see Statement#setMaxFieldSize(int)
	 * @return this
	 */
	public StmtOptions setMaxFieldBytes(int bytes) throws JdbxException
	{
		set(StmtOption.MAXFIELDSIZE, Integer.valueOf(bytes));
		return this;
	}


    /**
     * Returns the maximum number of bytes that can be
     * returned for character and binary column values in a result.
	 * @return the maximum size in bytes
	 * @see Statement#getMaxFieldSize()
	 */
	public int getMaxFieldBytes() throws JdbxException
	{
		return get(StmtOption.MAXFIELDSIZE).intValue();
	}


	/**
	 * Sets the limit for the maximum number of rows that any result generated by this statement 
	 * can contain to the given number. If the limit is exceeded, the excess rows are silently dropped. 
	 * @param count the maximum number
	 * @return this
	 * @see Statement#setLargeMaxRows(long)
	 */
	public StmtOptions setLargeMaxRows(long count) throws JdbxException
	{
		set(StmtOption.LARGEMAXROWS, Long.valueOf(count));
		return this;
	}


	/**
	 * Returns the limit for the maximum number of rows that any result generated by this statement 
	 * can contain. 
	 * @return the maximum number of rows. Zero means there is no limit.
	 * @see Statement#getLargeMaxRows()
	 */
	public long getLargeMaxRows() throws JdbxException
	{
		return get(StmtOption.LARGEMAXROWS).longValue();
	}


	/**
	 * Calls {@link Statement#setMaxRows(int)}.
	 * @param count the maximum number
	 * @return this
	 */
	public StmtOptions setMaxRows(int count) throws JdbxException
	{
		set(StmtOption.MAXROWS, Integer.valueOf(count));
		return this;
	}


	/**
	 * Returns {@link Statement#getMaxRows()}.
	 * @return the maximum number of rows
	 */
	public int getMaxRows() throws JdbxException
	{
		return get(StmtOption.MAXROWS).intValue();
	}


	/**
	 * Calls {@link Statement#setQueryTimeout(int)}.
	 * @param seconds the timeout in seconds
	 * @return this
	 */
	public StmtOptions setQueryTimeoutSeconds(int seconds) throws JdbxException
	{
		set(StmtOption.QUERYTIMEOUT, Integer.valueOf(seconds));
		return this;
	}


	/**
	 * Returns {@link Statement#getQueryTimeout()}.
	 * @return the timeout in seconds
	 */
	public int getQueryTimeoutSeconds() throws JdbxException
	{
		return get(StmtOption.QUERYTIMEOUT).intValue();
	}


	/**
	 * Calls {@link Statement#setEscapeProcessing(boolean)}.
	 * @param enable the flag
	 * @return this
	 */
	public StmtOptions setEscapeProcessing(boolean enable) throws JdbxException
	{
		set(StmtOption.ESCAPEPROCESSING, Boolean.valueOf(enable));
		return this;
	}


	/**
	 * Calls {@link Statement#setFetchDirection(int)}.
	 * @param direction the fetch direction enum
	 * @return this
	 */
	public StmtOptions setFetchDirection(FetchDirection direction) throws JdbxException
	{
		Check.valid(direction, "direction");
		set(StmtOption.FETCHDIRECTION, Integer.valueOf(direction.getCode()));
		return this;
	}


	/**
	 * Returns {@link Statement#getFetchDirection()} as enum value.
	 * @return the fetch direction
	 */
	public FetchDirection getFetchDirection() throws JdbxException
	{
		return FetchDirection.MAP.forCode(get(StmtOption.FETCHDIRECTION));
	}


	/**
	 * Calls {@link Statement#setFetchSize(int)}.
	 * @param rows the fetch size
	 * @return this
	 */
	public StmtOptions setFetchRows(int rows) throws JdbxException
	{
		set(StmtOption.FETCHSIZE, Integer.valueOf(rows));
		return this;
	}


	/**
	 * Returns {@link Statement#getFetchSize()}.
	 * @return the fetch size
	 */
	public int getFetchRows() throws JdbxException
	{
		return stmt_.get(Statement::getFetchSize).intValue();
	}


	/**
	 * Returns {@link Statement#isCloseOnCompletion()}
	 * @return the flag
	 */
	public boolean isCloseOnCompletion() throws JdbxException
	{
		return get(StmtOption.CLOSEONCOMPLETION).booleanValue();
	}


	/**
	 * Calls {@link Statement#closeOnCompletion()}
	 */
	public void setCloseOnCompletion() throws JdbxException
	{
		stmt_.call(Statement::closeOnCompletion);
	}


	/**
	 * Returns {@link Statement#getResultSetHoldability()} as enum value.
	 * You can set the holdability when you initialize the JDBX statement.
	 * @return the holdability
	 */
	public Holdability getResultHoldability()
	{
		return holdability_;
	}


	void setResultHoldability(Holdability value)
	{
		holdability_ = value;
	}


	/**
	 * Returns {@link Statement#getResultSetConcurrency()} as enum value.
	 * You can set the concurrency when you initialize the JDBX statement.
	 * @return the concurrency
	 */
	public Concurrency getResultConcurrency()
	{
		return concurrency_;
	}


	void setResultConcurrency(Concurrency value)
	{
		concurrency_ = value;
	}


	/**
	 * Returns {@link Statement#getResultSetType()} as enum value.
	 * You can set the result type when you initialize the JDBX statement.
	 * @return the result type
	 */
	public ResultType getResultType()
	{
		return resultSetType_;
	}


	void setResultType(ResultType value)
	{
		resultSetType_ = value;
	}
	
	
	private <T> void set(StmtOption<T> option, T value)
	{
		Unchecked.accept(option.setter, stmt_.getJdbcStmt(), value);
	}


	private <T> T get(StmtOption<T> option)
	{
		return Unchecked.apply(option.getter, stmt_.getJdbcStmt());
	}

	
	private final Stmt stmt_;
	private ResultType resultSetType_ = ResultType.FORWARD_ONLY;
	private Concurrency concurrency_ = Concurrency.READ_ONLY;
	private Holdability holdability_ = Holdability.CLOSE_AT_COMMIT;
}
